language: scala

scala:
  - 2.12.10

jdk:
  - openjdk8
  - openjdk11

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # Default stage test is already added
    - name: maven plugin
      script:
        - sbt 'set version in ThisBuild := "SET-BY-SBT-SNAPSHOT"' stryker4s-core/publishM2 # So maven can find the dependency
        - cd runners/maven
        - mvn test -B
      jdk: openjdk11
    - name: sbt plugin scripted tests
      script: sbt publishLocal scripted
      jdk: openjdk11
    - name: Test formatting
      script: ./bin/scalafmt --test
      jdk: openjdk11
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release
      jdk: openjdk11
      env:
        - CI_RELEASE=stryker4sPublishSigned
        - CI_SNAPSHOT_RELEASE=stryker4sPublish
        - CI_SONATYPE_RELEASE=stryker4sReleaseAll

# Matrixed with jdk's
script: sbt clean coverage test coverageReport

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache    -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt           -name "*.lock"               -print -delete
  # Don't cache built dependencies
  - find $HOME/.ivy2/         -name "*stryker4s*"          -print -exec rm -rf {} +
  - find $HOME/.m2/repository -name "*stryker4s*"          -print -exec rm -rf {} +

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.m2/repository
    - $HOME/.cache/coursier

before_install:
  # Ensure that git tags are always fetched so that sbt-dynver can pick up the correct version
  - git fetch --tags
