language: scala

scala:
  - 2.12.8

jdk:
  - oraclejdk8
  - openjdk11

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    # Default stage test is already added
    - name: Test formatting
      script: ./bin/scalafmt --test || (c=$?; echo "Format your files by running ./bin/scalafmt"; (exit $c))
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release
      jdk: openjdk11

script: sbt clean coverage test coverageReport

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  # These directories are cached to S3 at the end of the build
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  # Ensure that git tags are always fetched so that sbt-dynver can pick up the correct version
  - git fetch --tags
